// import "./globals.css";
import { Providers } from "@/redux/provider";
import {MantineProvider, ColorSchemeScript } from "@mantine/core";
import { NextAppDirEmotionCacheProvider } from 'tss-react/next/appDir';
import { theme } from './lib/theme';
import '@mantine/core/styles.css'
import Link from 'next/link';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme='dark' />
      </head>
      <body>
        <nav style={{ height: "80px", paddingLeft: "50px" }}>
          <Link href='/'><h3>Home</h3></Link>
        </nav>
      <NextAppDirEmotionCacheProvider options={{ key: 'css' }}>
      <MantineProvider defaultColorScheme='dark' theme={theme}>
        <Providers>{children}</Providers>
      </MantineProvider>
      </NextAppDirEmotionCacheProvider>
      </body>
    </html>
  );
}
